# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogDb:
    container_name: catalogDb
    image: mongo
  basketDb:
    container_name: basketDb
    image: redis
  rabbitMq:
    container_name: rabbitMq
    image: rabbitmq:3-management-alpine
    
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
      
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile
   
